# Generated by Django 4.0.3 on 2022-03-22 18:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='date_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
